[[constraint]]
  name = "github.com/nlopes/slack"
  # No constraint on nlopes/slack. We should always work with HEAD

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/lusis/slack-test"
  branch = "v2"